### PR TITLE
Github Actions CI part 2

### PR DESCRIPTION
**Pull request by kinggoesgaming**
Related issue: #484 
Previous PR: #486

### CODE REVIEW

**Comment by kinggoesgaming** [comment]
bots r+

**Comment by Dylan-DPC** [comment]
@kinggoesgaming how do we test this? :D

**Comment by kinggoesgaming** [comment]
> @kinggoesgaming how do we test this? :D

After this PR is merged, I will work on merging other PRs and while work on 2 PRs: one extending CI for other Travis CI stuff and one for a replacement for `bors`.

**Review by Dylan-DPC — APPROVED** [review]

**Comment by kinggoesgaming** [comment]
bors try

**Comment by kinggoesgaming** [comment]
As the bors rests are passing but bors itself is failing I am merging as is

**Pull request merged**
