### PR TITLE
Split up parse_str.rs file #236

### PR DESCRIPTION
**Pull request by murrayjbrown**
**I'm submitting a refactor for issue #236 - Split up parse_str.rs file.**

# Description

The file _bench/parse_str.rs_ has been refactored into:

> valid_parse_str.rs
> invalid_parse_str.rs
> slog_support/parse_str.rs

The test case `bench_parse()` has been split into `bench_parse_invalid_strings()` or `bench_parse_valid_strings()`, accordingly, for its respective test file;

Additionally, the test case `bench_log_discard_kv()` in _slog_support/parse_str.rs_ has been revised to produce benchmark results, which (for some reason) it did not previously.

# Motivation

Benchmarking file becoming too large.

# Tests

Benchmark test results should display test cases grouped according to description above. Attached are results for benchmark tests run _before_ and _after_ this refactoring:
* [uuid_bench_before.txt](https://github.com/uuid-rs/uuid/files/2342840/uuid_bench_before.txt)
* [uuid_bench_after.txt](https://github.com/uuid-rs/uuid/files/2342839/uuid_bench_after.txt)

# Related Issue(s)
#236

### CODE REVIEW

**Comment by kinggoesgaming** [comment]
@murrayjbrown thanks again for the working on this!! Can you run `cargo +nightly fmt` using the latest nightly?

**Comment by Dylan-DPC** [comment]
Thanks @murrayjbrown 

bors: r+

**Comment by murrayjbrown** [comment]
@kinggoesgaming I'm hoping that's now a rhetorical question about `cargo fmt` as the issue has been closed but I'll be sure to do so in the future.

Thanks to both you and @Dylan-DPC ! This has been a great intro to Rust. :-)

**Comment by Dylan-DPC** [comment]
@murrayjbrown yeah you don't have to bother about it since I pulled in your fork and ran fmt since it is trivial enough and didn't want to wait for you :smile: 

Thanks for the PR. Looking forward to more collaboration from you :+1:

**Pull request merged**
