### PR TITLE
remove fmt from travis

### PR DESCRIPTION
**Pull request by kinggoesgaming**

### CODE REVIEW

**Comment by kinggoesgaming** [comment]
@uuid-rs/uuid can you approve/merge once this passed?

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by kinggoesgaming** [comment]
@Dylan-DPC can you approve :P

**Comment by Dylan-DPC** [comment]
thought i clicked approve before this :D 

given that they'll be many changes coming up, i'm tempted of removing the requirement for approval so that it is easier to get the changes in. i'm checking the changes anyway but don't want to get blocked on it. thoughts?

**Review by Dylan-DPC — APPROVED** [review]

**Comment by kinggoesgaming** [comment]
@Dylan-DPC we can probably take that discussion elsewhere :)

bors r+

**Pull request merged**
