### PR TITLE
Add support for borsNG bot

### PR DESCRIPTION
**Pull request by kinggoesgaming**
* [x] need to patch `.travis.yml`

### CODE REVIEW

**Comment by kinggoesgaming** [comment]
waiting on appveyor integration

**Comment by kinggoesgaming** [comment]
bors: try

**Comment by kinggoesgaming** [comment]
This was expected: need to patch `.travis.yml` to not build any `*.tmp` file

**Comment by kinggoesgaming** [comment]
bors: r+

**Comment by kinggoesgaming** [comment]
bors: r-

**Comment by kinggoesgaming** [comment]
Should get a review before merging

**Comment by KodrAus** [comment]
Thanks for getting this all set up @kinggoesgaming!

**Pull request merged**
