### PR TITLE
Merge master breaking

### PR DESCRIPTION
**Pull request by kinggoesgaming**
**I'm submitting a ...**
  - [ ] bug fix
  - [ ] feature enhancement
  - [ ] deprecation or removal
  - [ ] refactor

# Description
Merge master into breaking

# Motivation
As breaking branch becomes the main branch, it is important to have changes there.
Routine merges

# Tests
All passing

# Related Issue(s)
N/A

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by kinggoesgaming** [comment]
oh no... i did against wrong branch

**Comment by kinggoesgaming** [comment]
bors: try

**Comment by kinggoesgaming** [comment]
bors: r+

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by kinggoesgaming** [comment]
bors: r+

**Comment by kinggoesgaming** [comment]
bors: r+

**Pull request merged**
