### PR TITLE
Fix macro hygiene

### PR DESCRIPTION
**Pull request by teohhanhui**
Re-export Ok and Err

### CODE REVIEW

**Comment by teohhanhui** [comment]
Easy way to trigger the problem:

```rust
use anyhow::Ok;
use uuid::{uuid, Uuid};

const SOME_UUID: Uuid = uuid!("00000000-0000-0000-0000-000000000000");
```

Example of error message when running into this macro hygiene issue:

```
error[E0532]: expected tuple struct or tuple variant, found function `Ok`
```

**Comment by teohhanhui** [comment]
ping @KodrAus

**Comment by KodrAus** [comment]
Thanks for the PR @teohhanhui!

This looks good to me, but would you be happy to add a test case [here](https://github.com/uuid-rs/uuid/tree/main/tests/ui/compile_pass) that exercises it? You could replace the `anyhow::Ok` in your repro with `type Ok = ()` or something like that.

**Comment by teohhanhui** [comment]
Done.

**Review by KodrAus — APPROVED** [review]
Thanks for fixing this up @teohhanhui!

**Pull request merged**
