### PR TITLE
Fix unspecified direct object in README

### PR DESCRIPTION
**Pull request by cedric-h**
**I'm submitting a grammar fix for the README**

# Description
Previously, the README contained "They are particularly useful in distributed systems, *though can be used*..."
To a native speaker, this sounds a little strange, whereas "They are particularly useful in distributed systems, though **they** can be used..." is clearer and more grammatically correct.

# Motivation
I'd like to make the README easier to understand

# Tests
I read it out loud and it sounded better and made more sense.

# Related Issue(s)
N/A

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by kinggoesgaming** [comment]
HA! 

We forgot to review it

**Pull request merged**
