### PR TITLE
Cargo cleanups

### PR DESCRIPTION
**Pull request by kinggoesgaming**
**I'm submitting a ...**
  - [ ] bug fix
  - [ ] feature enhancement
  - [ ] deprecation or removal
  - [x] refactor

# Description
* Clean up `Cargo.toml`
* fix `const-fn` -> `const_fn`

# Motivation
Clarity

# Tests
N/A

# Related Issue(s)
N/A

### CODE REVIEW

**Comment by kinggoesgaming** [comment]
@Dylan-DPC how do we go about with this?

**Comment by Dylan-DPC** [comment]
@kinggoesgaming I am fine with all the changes except the one that changes the feature name

**Comment by kinggoesgaming** [comment]
@Dylan-DPC KodrAus agrees that we should matching the unstable features same as their rust builtin feature names

image

**Comment by Dylan-DPC** [comment]
bors: r+

**Pull request merged**
