### PR TITLE
merge master into  breaking

### PR DESCRIPTION
**Pull request by kinggoesgaming**
**I'm submitting a ...**
  - [ ] bug fix
  - [ ] feature enhancement
  - [ ] deprecation or removal
  - [ ] refactor

# Description
Merge `master` into `breaking` via a proxy branch

# Motivation
Get the master changes into the current main branch `breaking`

# Tests
current tests passing

# Related Issue(s)
N/A

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by kinggoesgaming** [comment]
`WIP` bot is sleeping again :( .. Imma temporarily remove the requirement

**Pull request merged**
