### PR TITLE
fix parser::Error::InvalidCharacter Display message

### PR DESCRIPTION
**Pull request by kinggoesgaming**
**I'm submitting a(n)** bug fix

# Description
Use string instead of `str::Chars`

# Motivation
While working on `uuid_cli` I realized that when an invalid character was provided in a namespace uuid for v3 and v5 variants, the expected characters is shown as a numeric array instead of an array of chars. Not helpful for users. 

# Tests
As its only a error message change, no tests needed

# Related Issue(s)
N/A

### CODE REVIEW

**Comment by KodrAus** [comment]
The build failure looks like a combination of formatting needed and wasm.

**Comment by kinggoesgaming** [comment]
Ill get to it tonight :+1:

**Comment by kinggoesgaming** [comment]
awaiting on #358

**Pull request merged**
