### PR TITLE
Prepare for 0.8.1 release

### PR DESCRIPTION
**Pull request by KodrAus**
Includes #434 

There aren't any code changes in this release, it just includes some additional documentation.

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
Already 0.8.1? :D

**Comment by KodrAus** [comment]
Since it’s just docs I can’t see any reason to hold off on publishing 🙂

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by kinggoesgaming** [comment]
Bots r+

**Comment by kinggoesgaming** [comment]
Bors r+

**Pull request merged**
