### PR TITLE
add endian adapters

### PR DESCRIPTION
**Pull request by kinggoesgaming**
**I'm submitting a(n)** feature

# Description
Add `uuid::adapter::endian::{Big, Little}`.

# Motivation
Currently we have single representation for `uuid::Uuid` in-memory. However people have needed for little endian. Particularly bindings have a requirement of the memory layout (see #406).

# Tests
Currently new tests are needed to be added

# Related Issue(s)
#406

### CODE REVIEW

**Comment by kinggoesgaming** [comment]
@uuid-rs/uuid I need your input on this. I want to make sure I am doing this correct before I add serde and other content to this PR

**Comment by Dylan-DPC** [comment]
looks good to me but good to get an opinion from @KodrAus as well

**Comment by kinggoesgaming** [comment]
psss.. @KodrAus opinions?

**Comment by KodrAus** [comment]
Hmm, I think having types specifically for this might be clumsy to use in practice, because what you really want is a `Uuid`, rather than a newtype that wraps it.

What if we have two functions: `from_u128_be` and `from_u128_le` and either deprecate the `From<u128>` impl or note in the docs that it's platform-dependent? (personally I'd be leaning towards deprecating because it's a bit of a footgun)

**Comment by kinggoesgaming** [comment]
> Hmm, I think having types specifically for this might be clumsy to use in practice, because what you really want is a `Uuid`, rather than a newtype that wraps it.
> 
> What if we have two functions: `from_u128_be` and `from_u128_le` and either deprecate the `From<u128>` impl or note in the docs that it's platform-dependent? (personally I'd be leaning towards deprecating because it's a bit of a footgun)

1. `From<u128>` impl was already removed in #407
2. I was thinking that all the `_be` and `_le` methods be moved to respective endian adapters. This includes the `to_fields_{be,le}`.

**Comment by KodrAus** [comment]
What do we expect a caller to do with a `endian::Big` or `endian::Little`? If its only purpose is to act as a point on your way to a `Uuid` then it seems like the difference between:

```rust
use uuid::{Uuid, adapter::endian};

let uuid: Uuid = endian::Big::from(my_u128).into();
```

or

```rust
use uuid::Uuid;

let uuid = Uuid::from_u128_be(my_u128);
```

But if there's something else these adapters would do then maybe they are worth having as separate structs.

**Comment by kinggoesgaming** [comment]
One big one I can think is (de)serialization. Especially given that you that uuid is stored in a particular endian and you don't to risk messing up..

That aside I am fine with providing the methods on `Uuid` itself

**Comment by kinggoesgaming** [comment]
@uuid-rs/uuid can I have a resolution on which way I should go on this so I can finish this PR then finish the few documentation bits I want to have in this for the release?

**Comment by KodrAus** [comment]
I'm happy for you to take this in the direction you feel is most appropriate.

Personally, I think a combination of constructor methods on `Uuid`, and a serialization module like [`adapter::compact`](https://docs.rs/uuid/0.7.4/uuid/adapter/compact/index.html) would be the most consistent with how we already do things.

**Comment by kinggoesgaming** [comment]
> I'm happy for you to take this in the direction you feel is most appropriate.
> 
> Personally, I think a combination of constructor methods on `Uuid`, and a serialization module like [`adapter::compact`](https://docs.rs/uuid/0.7.4/uuid/adapter/compact/index.html) would be the most consistent with how we already do things.

I think that's a good compromise :)

**Comment by kinggoesgaming** [comment]
@KodrAus I should close this... since your PR technically superseded this one

**Comment by KodrAus** [comment]
Ah yes that's right. Thanks @kinggoesgaming, I'll close this one now.

**Pull request closed without merging**
