### PR TITLE
Fix minimum required cfg_if version

### LINKED ISSUE #205: Invalid dependency specification for cfg-if
**Note: for support questions, please use [gitter] or [users forums]**. This 
repository's issues are reserved for feature requests and bug reports.

[gitter]: https://gitter.im/uuid-rs/Lobby
[users forums]: https://users.rust-lang.org

**I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note 
  at the top of this template.

# Description
cfg_if without an else block (which is used by uuid in `src/lib.rs`) is not supported until 0.1.2, see https://github.com/alexcrichton/cfg-if/commit/8a594d0994b5c37f3cad035a6c76ae0105bce013

# Bug Report

## Steps to Reproduce

1. ...
2. ...
3. ...

## Environment

- Version: 
- Target: 
- Features: 

## Meta

# Feature Request

# Other

### PR DESCRIPTION
**Pull request by jethrogb**
cfg_if without an else block is not supported until 0.1.2, see https://github.com/alexcrichton/cfg-if/commit/8a594d0994b5c37f3cad035a6c76ae0105bce013

**I'm submitting a ...**
  - [x] bug fix
  - [ ] feature enhancement
  - [ ] deprecation or removal
  - [ ] refactor

# Description

# Motivation

# Tests

# Related Issue(s)

Fixes #205

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
Thanks for the PR.

**Comment by jethrogb** [comment]
The dependency on this version was already there implicitly. This crate does not compile with `cfg_if` lower than 0.1.2. This PR just makes the dependency explicit.

**Comment by kinggoesgaming** [comment]
ah ok... waiting on the status to be cleared

**Comment by Dylan-DPC** [comment]
yeah i agree. wasn't a breaking change. 

@kinggoesgaming appveyor is bugged for some reason

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by kinggoesgaming** [comment]
As the Apveyor PR passed, waiving the requirement should be fine

**Comment by Dylan-DPC** [comment]
@kinggoesgaming yeah but it got cancelled for some reason

**Comment by kinggoesgaming** [comment]
bors: r+

**Pull request merged**
