### PR TITLE
make uuid structs repr(transparent)

### LINKED ISSUE #463: make Uuid #[repr(transparent)]
Based on #461 by @DianaNites

---
The crate supports `no_std`, but the Uuid type isn't FFI safe/`repr(transparent)`? There doesn't seem to be any reason for it not to be. That attribute is stable since `1.28.0`, which is below the crates MSRV.

### PR DESCRIPTION
**Pull request by kinggoesgaming**
**I'm submitting a(n)** feature

# Description
Make the following structs `#[repr(transparent)]`:
* `Uuid`
* `Hyphenated`
* `HyphenatedRef`
* `Simple`
* `SimpleRef`
* `Urn`
* `UrnRef`

# Tests
Tests should pass as is

# Related Issue(s)
closes #463

### CODE REVIEW

**Comment by kinggoesgaming** [comment]
An update: I have been trying to get the one heck of a mess that is our build system fixed. This might take sometime to get fixed. I want a good fix not just a system held together with duct tape.

But I am definitely want this merged ASAP.

**Comment by kinggoesgaming** [comment]
@uuid-rs/uuid  :)

**Comment by KodrAus** [comment]
I'm on board with marking `Uuid` as `#[repr(transparent)]`. I'm not sure we need to commit to marking its display adapters as transparent though, do we? I could imagine wanting to capture some other formatting information in some of them one day, like what case to use for `a` - `f`.

**Comment by kinggoesgaming** [comment]
> 
> 
> I'm on board with marking `Uuid` as `#[repr(transparent)]`. I'm not sure we need to commit to marking its display adapters as transparent though, do we? I could imagine wanting to capture some other formatting information in some of them one day, like what case to use for `a` - `f`.

@KodrAus fair enough! I will remove the attribute from the adapters

**Comment by kinggoesgaming** [comment]
@KodrAus anything else?

**Review by KodrAus — APPROVED** [review]
This looks good to me!

**Pull request merged**
