### PR TITLE
Clarify documentation around the relation to the rand crate

### PR DESCRIPTION
**Pull request by carols10cents**
**I'm submitting a(n)** other - documentation improvement

# Description

The rand crate changed its trait names, so these docs were referencing a
trait that doesn't exist in the current version of rand. Change to be a
bit more vague to avoid this getting out of date again.

Also "use rand instead" wasn't very clear because "rand" doesn't contain
something clearly equivalent like `get_uuid_v4`. To be clearer, add a
reference to the `Builder::from_bytes` function in this crate.

# Motivation

It took me a few minutes to figure out what this documentation was saying, and I'd like to save someone else those few minutes in the future.

# Tests

N/A

# Related Issue(s)

None

### CODE REVIEW

**Comment by kinggoesgaming** [comment]
Hi can you merge changes from master and then I can merge

**Comment by carols10cents** [comment]
Done!

**Pull request merged**
