### PR TITLE
Add COPYRIGHT file and add license headers to all rs files

### PR DESCRIPTION
**Pull request by kinggoesgaming**
**I'm submitting a ...**
  - [ ] bug fix
  - [ ] feature enhancement
  - [ ] deprecation or removal
  - [ ] refactor

# Description
* Add a `COPYRIGHT` file
* Add the license header to all `.rs` files, not just `lib.rs`

# Motivation
N/A

# Tests
N/A

# Related Issue(s)
N/A

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
Do we need the copyright considering that the licence files actually enforce the copyright?

**Comment by kinggoesgaming** [comment]
Its usually a good way to put it outright for anyone who starts at the root of the repo... its right there and can read it as they want before they even get to reading a source file

Also the crate sources will include it

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by kinggoesgaming** [comment]
I think lately nightly rustfmt removed --write-mode

**Comment by Dylan-DPC** [comment]
bors: r+

**Pull request merged**
