### PR TITLE
make Uuid a newtype

### PR DESCRIPTION
**Pull request by kinggoesgaming**
**I'm submitting a ...**
  - [ ] bug fix
  - [ ] feature enhancement
  - [ ] deprecation or removal
  - [x] refactor

# Description
* Convert `Uuid` into a newtype.
* Use `Uuid::from_uuid_bytes` (as the main constructor) to construct a `Uuid` where possible

# Motivation
We treat `Uuid` like a newtype, this makes it more obvious

# Tests
All tests passing

# Related Issue(s)
#266

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
What's the gain in these?

**Comment by kinggoesgaming** [comment]
@Dylan-DPC  As far as there is a particular gain. However, I am preparing this for consistency as the the new adapters will be newtypes (see #256)

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by Dylan-DPC** [comment]
Nightly builds failed due to https://github.com/rust-lang/rust/issues/51699

**Comment by Dylan-DPC** [comment]
bors: try

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by kinggoesgaming** [comment]
bors retry

**Pull request merged**
