### PR TITLE
refactored code to use const_ft

### PR DESCRIPTION
**Pull request by Dylan-DPC**
**I'm submitting a(n)** refactor

# Description
Adds const_ft(0.1.2) as a dependency
Refactors code to use the dependency

# Motivation
Code looks cleaner and avoids const(feature) & const(not-feature) repetition

# Tests
All tests pass, none added

### CODE REVIEW

**Comment by KodrAus** [comment]
Hmm, I think we should be really mindful about introducing new dependencies. Do we need to use an external crate for const functions? Using a macro seems nice, but it could easily just live here in `uuid`.

**Comment by kinggoesgaming** [comment]
As there some problems with the macro in itself, I think its best to not depend on it either way until they are polished out

**Comment by Dylan-DPC** [comment]
@kodrAus it doesn't make much of a difference since it's my own crate. Though currently there are some issues with the macro so might postpone this

**Comment by KodrAus** [comment]
@Dylan-DPC there are a few differences worth considering. The first is compile times where additional dependencies mean more units of compilation, more metadata, more network, so they'll regress slightly. The second is in mental overhead, where there's an additional non-local piece of infrastructure new contributors need to understand in order to contribute.

I'm not suggesting those are hard blockers, but we should definitely consider them.

**Comment by Dylan-DPC** [comment]
@KodrAus I understand your point and it was a reason why i wasn't so keen on `cfg_if`. One of the main reasons of creating a new crate is that it wasn't related to uuids and can be something of greater use to other projects as well.

 Turns out there is still some more stuff to be done with the macros so closing the PR now and we can reconsider it later.

**Pull request closed without merging**
