### PR TITLE
Upgrade rand to 0.7

### PR DESCRIPTION
**Pull request by mati865**
**I'm submitting a(n)** (other)

# Description

# Motivation
Getting rid of old rand versions.

# Tests

Ran `cargo test` on Linux.

# Related Issue(s)

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
Thanks for the PR. We had to close a similar effort earlier because of https://github.com/uuid-rs/uuid/pull/417

**Comment by mati865** [comment]
Getrandom became `no_std` crate, I'll see if it still fails.

**Comment by mati865** [comment]
I'll open issue in getrandom repo, sorry for the noise.

**Comment by Dylan-DPC** [comment]
No problem and thanks for opening the issue. When you have done so, leave a comment here.

**Comment by mati865** [comment]
The issue is basically https://github.com/rust-random/getrandom/issues/4
It can be worked around by bumping MSRV to 1.32: https://travis-ci.com/mati865/uuid/builds/123603614 but it's not strictly `no_std`.

**Pull request closed without merging**
