### PR TITLE
Add compatibility with rocket

### PR DESCRIPTION
**Pull request by LMH01**
**I'm submitting a feature**

# Description
This pull requests implements the traits [FromRequest](https://api.rocket.rs/v0.5-rc/rocket/request/trait.FromRequest.html) and [FromParam](https://api.rocket.rs/v0.5-rc/rocket/request/trait.FromParam.html) from the [web framework rocket](https://github.com/SergioBenitez/Rocket) to `Uuid`.

# Related Issue(s)
#649 
#651

### CODE REVIEW

**Comment by LMH01** [comment]
#649 and #651 are implemented

**Comment by LMH01** [comment]
@KodrAus
Could you please review this pull request?
It is ready.

**Comment by LMH01** [comment]
Another idea I just had: 
FromRequest currently only passes when the uuid is sent in an http header. I think it would be beneficial if it is also checked if a cookie named uuid exists if the http header does not exist.
This way the user would have two options to transmit the uuid to the request handler and they can decide which method to use.

I will implement that probably tomorrow.

**Comment by LMH01** [comment]
Review is ready again.

**Comment by a1phyr** [comment]
This already exists in `rocket`, but you need the `uuid` feature

**Pull request closed without merging**
