### PR TITLE
Remove dependency on serde_derive

### PR DESCRIPTION
**Pull request by coolreader18**
**I'm submitting a(n)** other

# Description
Remove the `serde_derive` feature from the `serde` dependency.
# Motivation
`serde_derive` is a pretty heavy dependency that adds a lot to compile times; as it's not used in this crate outside of tests, I figured it would be ok to remove it.
# Tests

n/a
# Related Issue(s)
#408 ?

### CODE REVIEW

**Comment by kinggoesgaming** [comment]
An update: I have been trying to get the one heck of a mess that is our build system fixed. This might take sometime to get fixed. I want a good fix not just a system held together with duct tape.

This is definitely on the timeline post fixing the CI infra.

**Comment by kinggoesgaming** [comment]
hey @coolreader18 

Thanks for contributing. Again sorry for the delay on getting to the PR

**Comment by coolreader18** [comment]
No problem, thanks for merging this!

**Pull request merged**
