### PR TITLE
use UuidBytes instead of [u8; 16]

### PR DESCRIPTION
**Pull request by kinggoesgaming**
**I'm submitting a ...**
  - [ ] bug fix
  - [ ] feature enhancement
  - [ ] deprecation or removal
  - [x] refactor

# Description
* Change from `[u8; 16]` to `UuidBytes` across files

# Motivation
Consistency

# Tests
All current tests pass

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by kinggoesgaming** [comment]
This is not a breaking change, as the actual signature stays the same

**Comment by kinggoesgaming** [comment]
bors try

**Comment by Dylan-DPC** [comment]
bors: r+

**Pull request merged**
