### PR TITLE
Rename Expected to ExpectedLength

### PR DESCRIPTION
**Pull request by kinggoesgaming**
**I'm submitting a(n)** refactor

# Description
Renamed `uuid::parser::Expected` to `uuid::parser::ExpectedLength`

# Motivation
`Expected` was slightly ambiguous.

# Tests
Current tests should pass as is. No new tests.

# Related Issue(s)
N/A

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
Need to run rustfmt

**Comment by kinggoesgaming** [comment]
@Dylan-DPC this should be ready to go

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by kinggoesgaming** [comment]
we need to switch from `rustfmt-preview` to `rustfmt` component

**Pull request merged**
