### PR TITLE
feat: add `prost` support

### LINKED ISSUE #715: Add `prost::Message` implementation for `Uuid`
## Motivation
[Prost](https://github.com/tokio-rs/prost) is a [Protocol Buffers](https://developers.google.com/protocol-buffers/) implementation for the [Rust Language](https://www.rust-lang.org/). Protocol Buffers are used as the message exchange format for [gRPC](https://grpc.io/). Clients and servers need to build and parse protocol messages. The Prost crate has a code generator to transform .proto files into Rust types that implement the `prost::Message` trait to simplify message encoding/decoding. When working with `Uuid`s, it's common to have to write boilerplate to handle transforming between whatever the code gen'd type is and the proper `Uuid` type.

## Solution
The Prost crate has support to use existing Rust types rather than generating new types provided those existing types implement the `prost::Message` trait. Thus, the solution is to add a `prost::Message` implementation behind a feature flag.

```rust
// Raw encoding
#[cfg(feature = "prost-bytes")]
impl prost::Message for Uuid ..

// String Encoding
#[cfg(feature = "prost-hyphenated")]
impl prost::Message for Uuid ..
```

One challenge is that Protobuf users may require a particular encoding format, and so a decision would need to be made about which formats to support or whether to support all the encoding formats implemented by this crate. I have included the two more common formats in the above example, but perhaps a user would need an alternative encoding like urn.

## Alternatives
- Continue writing boilerplate to convert between a generated Uuid struct (typically the equivalent of `struct Uuid(Vec<u8>)` and the uuid-rs `Uuid` type.
- Implement a 3rd crate to get around the orphan trait rules; this still requires a newtype and some boilerplate but is a bit less boilerplate than the first alternative.

## Is it blocking?
No

## Anything else?
Prost is a rather mature crate in the tokio organization that has quite a bit of adoption and has likely cemented its place in the Rust ecosytem. Adding a feature to interoperate with prost is unlikely to result in feature churn.

### PR DESCRIPTION
**Pull request by aymanalqadhi**
Pull request to add support for `prost` crate by implementing `prost::Message` for `uuid::Uuid`.

Resolves #715

### CODE REVIEW

**Comment by jwilm** [comment]
Hi @aymanalqadhi, 

Wow, I was not expecting someone else to make a PR for my issue! This is exciting to see.

I believe this only _partially_ addresses #715 because this only supports the _hyphenated string_ serialization. In my proposal, I suggested that we start with two feature flags, one for the hyphenated encoding and one for a binary encoding. I would be in support of merging a PR like this if the feature flag were renamed to something like `prost-hyphenated` to allow for additional encoding variants.

**Comment by aymanalqadhi** [comment]
I think a better name for the feature would be `prost-string` or something, since basic hex-encoded values are also supported.

**Comment by lilymara-onesignal** [comment]
Hi, can I ask why this PR got closed? It's a pretty nice feature to have for people using UUIDs in gRPC services, it would be great if we could get it merged in.

**Comment by jwilm** [comment]
> Hi, can I ask why this PR got closed? It's a pretty nice feature to have for people using UUIDs in gRPC services, it would be great if we could get it merged in.

It was identified in the feature request issue that the approach of using feature flags would make serialization strategies mutually exclusive. This would prevent the ability to write applications that talk to services using alternative serialization strategies.

I think the next step would be considering how prost might be able to support such a use case without requiring newtypes.

**Comment by aymanalqadhi** [comment]
What if a specific format (let's say binary) is used as the default, and is enabled automatically when specifying the `prost` feature. And a second feature (e.g., `prost-string`) can be used to switch to the string format?

**Comment by KodrAus** [comment]
Crate features just aren't suitable for this kind of configuration because you don't have control over what features are activated in your dependency graph, so if you end up in a situation where two dependencies set incompatible features then you'll have no way to remedy things. Worse still, you won't know they're wrong until you've possibly already encoded protobufs with the wrong format, which is spongy enough on the wire that it may even just silently work.

If we can come up with an approach that isn't reliant on crate features then I'd be more than happy to revisit this 🙂

-----

For what it's worth, I tend to separate these kinds of interchange types from whatever richer model is used within a service itself and map between them. That way your protos can work in terms of the simplest possible datatype, and your service can work with the most useful. Rust makes that pattern both cheap and difficult to get wrong.

**Comment by aymanalqadhi** [comment]
I totally get your point. The approach I suggested does not depend on mutually exclusive feature flags.

If the idea of using multiple feature flags is out of the question, then perhaps supporting a single format (string is probably the most used, albeit less efficient) should suffice for most users.

**Comment by jwilm** [comment]
> If the idea of using multiple feature flags is out of the question, then perhaps supporting a single format (string is probably the most used, albeit less efficient) should suffice for most users.

As convenient as this would be _today_, I think it's not the right solution. Uuid is already 1.0 and values stability. Adding a prost flag feature that in any way makes assumptions about encoding format is eventually going to require a breaking change when a more robust solution becomes available.

**Pull request closed without merging**
